### ISSUE TITLE
Кажется Docker больше не собирается на maven.3.6.0-jdk-11.slim 

### ISSUE THREAD

**Issue by solar4live** [malikzh/NCANode#105]
**Describe the bug**
(пожалуйста не судите строго я новичок)

Устарели публичные сертификаты для хранилищ. 
В результате сборка контейнера ломается на строке 
RUN apt update && apt install -y crudini
поменял 
FROM maven:3.8.4-jdk-11-slim
всё собралось с первого раза. 
Но дальше началась путаница.

1/ все методы из API 2.0 возвращают:
{
    "message": "API version not supported",
    "status": 2
}

2/ 
{
    "result": {
        "dateTime": "2021-11-30 18:14:33",
        "timezone": "Asia/Almaty",
        "name": "NCANode v1.1.0",
        "version": "1.1.0"
    },
    "message": "",
    "status": 0
}
То есть что? Поставилась старая версия? 
зашел в контейнер - тем действительно лежит старый README.md 
в котором  не упоминается cms и прочие новые фичи.
а в исходнике, который слит из github в котором делал сборку - README.md - новый. 

это баг? или подскажите пожалуйста что я делаю не так?

**To Reproduce**
1. git clone https://github.com/malikzh/NCANode.git
2. переименовал Dockerfile.build в Dockerfile
3. исправил версию maven на 3.8.4
4. настроил прокси к докеру 
5. импортировал файл NCANode_2.0.postman_collection.json в Postman

**Comment by malikzh** [comment]
Добрый день. Посмотрите у себя в исходном коде, какая версия у вас в этом файле: https://github.com/malikzh/NCANode/blob/master/src/main/java/kz/ncanode/info/InfoServiceProvider.java#L9

**Comment by solar4live** [comment]
Добрый вечер, 
версия 2.3.0

Начало файла:
import kz.ncanode.ioc.ServiceProvider;

/**
 * Класс хранит информацию о запущенной ноде
 */
public class InfoServiceProvider implements ServiceProvider {
    public final static String VERSION = "2.3.0";
    public final static String PROJECT_PAGE = "https://ncanode.kz";
    public final static String GITHUB_PAGE = "https://github.com/malikzh/NCANode";
....

**Comment by atlekbai** [comment]
Проблема с отсутствием публичных ключей. Выходит такая ошибка при сборке

```
W: GPG error: http://archive.ubuntu.com trusty-updates Release: The following signatures 
couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 
NO_PUBKEY 0E98404D386FA1D9
```


Решается это добавлением отсутствующих ключей.

```Dockerfile
FROM maven:3.6.0-jdk-11-slim
WORKDIR /usr/local/src/NCANode

## Решение проблемы
RUN apt-get update && apt-get install -y gnupg2
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138 && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9

RUN apt install -y crudini
# ...
```
