### ISSUE TITLE
Будет ли поддерживаться новый  алгоритм ЭЦП СТ РК ГОСТ Р 34.10-2015 ?

### ISSUE THREAD

**Issue by vprokof** [malikzh/NCANode#117]
НУЦ планирует на конец 2 квартал 2022 года — 18/25 июня.
Переход на один ключ ЭЦП, т.е. физическим и юридическим лицам будет выдаваться один ключ ЭЦП на алгоритме СТ РК ГОСТ Р 34.10-2015 (далее – ГОСТ 2015), который будет использоваться и для аутентификации, и для подписи.

Будет ли поддерживать NCANode новый алгоритм ЭЦП ?

**Comment by malikzh** [comment]
Да, в версии 3.0.0 я добавлю поддержку.
