### ISSUE TITLE
Поддержка новой версии kalkancrypt-0.7

### ISSUE THREAD

**Issue by vaavaa** [malikzh/NCANode#118]
Обновилась библиотека kalkancrypt-0.7,
Есть в планах поддержка новой версии библиотеки?

Информация об обновленной библиотеке:

"Уважаемые владельцы и разработчики информационных систем!

Национальный удостоверяющий центр Республики Казахстан сообщает о том, что проведены работы по обновлению комплекта разработчика НУЦ РК.
Обновленное SDK можно будет скачать по ссылке: http://pki.gov.kz/get-sdk. Данная ссылка будет активна постоянно.
Описание изменений (документационный файл «changelog.txt»):

   • Java
       ¤ New
           kalkancrypt-0.7 :
           - Добавление объектных идентификаторов для поддерживаемых типов хранилищ (ветка 1.2.398.3.3.5 Хранилище ключей)
           - Добавление KeyStoreInfo
           - Удаление заглушки SecretKeyFactory

           knca_applet-SNAPSHOT
           - Добавление подписания массива строк XML в методе sign
           - Исправление ошибок в работе с хранилищами
           - Сохранение расположения последнего успешно использованного PKCS12-хранилища в настройках

   • Тестовые сертификаты
       ¤ New
           - Добавлены новые тестовые действующие и отозванные сертификаты на алгоритме Гост Р 34.10-2015
           - Обновлены тестовые корневые сертификатыж

   • KalkanCryptCOM
       ¤ New
           v3.0.0.0
           - Добавлены алгоритмы ГОСТ Р 34.10-2015 и ГОСТ Р 34.11-2015;

       ¤ Bugfix:
           v3.0.0.1
           - Исправлена ошибка при проверке сертификата методом X509ValidateCertificate() с помощью CRL;
           - Исправлена ошибка при извлечении информации дельта-CRL, CRL, OCSP из сертификата, в котором данная информация отсутствует;
           - Исправлена ошибка при вызове всех методов в VBA, 1C, PHP и в других языках;

   • KalkanCrypt_C_Windows
       ¤ New
           v2.0.0.0
           - Добавлены алгоритмы ГОСТ Р 34.10-2015 и ГОСТ Р 34.11-2015;

       ¤ Bugfix:
           v2.0.0.1
           - Исправлена ошибка при проверке сертификата методом X509ValidateCertificate() с помощью CRL;
           - Исправлена ошибка при извлечении информации дельта-CRL, CRL, OCSP из сертификата, в котором данная информация отсутствует;

   • OpenSSL-libs:
       ¤ New
       - Добавлены статические и динамические библиотеки OpenSSL (Поддерживаемые алгоритмы Гост Р 34.10-2015, Гост 34.310-2004, RSA)  для ОС Linux и Windows"

**Comment by malikzh** [comment]
Поддержка будет. Я запросил новую версию комплекта разработчика. Ожидаю.
