### ISSUE TITLE
Старая версия в Docker

### ISSUE THREAD

**Issue by Eremiteb** [malikzh/NCANode#122]
Здравствуйте. 
Когда получаю docker-контейнер командой docker run -dti -p 14579:14579 malikzh/ncanode,
он собирается с файлами, созданными в марте 2019 года, а не свежими версиями, и соответственно, не поддерживает вторую версию api (в ответе - {"message":"API version not supported","status":2}). 

![Буфер обмена01](https://user-images.githubusercontent.com/6480199/189484439-3097da7b-b6ac-4808-9b86-0c8675328060.jpg)

**Comment by malikzh** [comment]
Взял в работу. Благодарю за обратную связь.

**Comment by malikzh** [comment]
Dockerfile в скором времени будет обновлен
