### ISSUE TITLE
Ошибка 500 при запросе cms.sign

### ISSUE THREAD

**Issue by Eremiteb** [malikzh/NCANode#123]
Здравствуйте.
Посылаю приложенный запрос, получаю ошибку {"httpCode":500,"message":"Api error: org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray","status":5}

[req.txt](https://github.com/malikzh/NCANode/files/9540424/req.txt)

**Comment by malikzh** [comment]
Здравствуйте!

В данный момент я работаю над версией 3.0:

https://github.com/malikzh/NCANode/tree/v3

Я исправлю этот баг в следующей версии.

Возможно Вы используете новые ключи ЭЦП с алгоритмом подписи ГОСТ-2015. Текущая версия NCANode этого не поддерживает.
