### ISSUE TITLE
Планируемые изменения НУЦ РК на 2022 год

### ISSUE THREAD

**Issue by Rashid2kaz** [malikzh/NCANode#129]
Поддерживает ли ваш сервер новые изменения запланированные НУЦ РК к 1 октября 2022 года?

P.S. Извиняюсь, если неправильно выразился.

**Comment by malikzh** [comment]
Здравствуйте. Я работаю над версией 3.0 #121 

Там будет поддержка новых ЭЦП GOST-2015.

**Comment by Rashid2kaz** [comment]
Хорошая новость)) Не хочу быть назойливым, а не подскажете когда примерно ожидать релиз? )

**Comment by malikzh** [comment]
На этих выходных планирую, но может быть +/- 1 неделя

**Comment by eudj1n** [comment]
@malikzh я для тестирования интеграции по своим проектам добавил новые библиотеки с поддержкой совместимости с текущей версией API, если кому-то нужно - могу отправить пулл реквест для апрува и включения в версию 2.3.1

**Comment by malikzh** [comment]
Теперь поддерживает. Осталось, выкатить релиз, обновить документацию и всё такое
