### ISSUE TITLE
Ошибка при проверки подписанной xml (XML.verify)

### ISSUE THREAD

**Issue by developeractiv** [malikzh/NCANode#130]
**Describe the bug**
При вызове метода XML.verify происходит ошибка: 
Missing implementation of resolved method 'abstract boolean engineCanResolve(org.w3c.dom.Element, java.lang.String, org.apache.xml.security.keys.storage.StorageResolver)' of abstract class org.apache.xml.security.keys.keyresolver.KeyResolverSpi.

Проблема в pom.xml
<dependency>
      <groupId>org.apache.santuario</groupId>
      <artifactId>xmlsec</artifactId>
      <version>2.3.0</version>
</dependency>

**Как пофиксить**
Поменять версию на 2.1.7

<dependency>
      <groupId>org.apache.santuario</groupId>
      <artifactId>xmlsec</artifactId>
      <version>2.1.7</version>
</dependency>

**Comment by malikzh** [comment]
Здравствуйте, благодарю за решение :)
