### ISSUE TITLE
Неактуальный README

### ISSUE THREAD

**Issue by AlibekMussin** [malikzh/NCANode#131]
Добрый день
В вашем общем ридми написано, что нужен калкан 0.6

А в папке lib написано, что нужен калкан 0.7

На сайте, что 0.4.

Можете как-то актуализировать документацию везде?

**Comment by malikzh** [comment]
В ближайшее время планируется релиз NCANode 3.0. В данный момент документация подготавливается и после релиза будет актуализирована везде.
