### ISSUE TITLE
Не билдится проект

### ISSUE THREAD

**Issue by abendankan** [malikzh/NCANode#134]
Добрый вечер! При запуске и билде выходит ошибка, 

java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

> ./gradlew bootRun --info
Initialized native services in: /home/daniyar/.gradle/native
Initialized jansi services in: /home/daniyar/.gradle/native
The client will now receive all logging from the daemon (pid: 22123). The daemon log file: /home/daniyar/.gradle/daemon/7.2/daemon-22123.out.log
Starting 4th build in daemon [uptime: 34 mins 51.409 secs, performance: 100%, non-heap usage: 25% of 256 MiB]
Using 8 worker leases.
Now considering [/home/daniyar/App/NCANode] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Settings evaluated using settings file '/home/daniyar/App/NCANode/settings.gradle'.
Projects loaded. Root project using build file '/home/daniyar/App/NCANode/build.gradle'.
Included projects: [root project 'NCANode']

> Configure project :
Evaluating root project 'NCANode' using build file '/home/daniyar/App/NCANode/build.gradle'.
Applying dependency management to configuration 'bootArchives' in project 'NCANode'
Applying dependency management to configuration 'archives' in project 'NCANode'
Applying dependency management to configuration 'default' in project 'NCANode'
Applying dependency management to configuration 'implementation' in project 'NCANode'
Applying dependency management to configuration 'compileOnly' in project 'NCANode'
Applying dependency management to configuration 'compileClasspath' in project 'NCANode'
Applying dependency management to configuration 'annotationProcessor' in project 'NCANode'
Applying dependency management to configuration 'runtimeOnly' in project 'NCANode'
Applying dependency management to configuration 'runtimeClasspath' in project 'NCANode'
Applying dependency management to configuration 'testImplementation' in project 'NCANode'
Applying dependency management to configuration 'testCompileOnly' in project 'NCANode'
Applying dependency management to configuration 'testCompileClasspath' in project 'NCANode'
Applying dependency management to configuration 'testAnnotationProcessor' in project 'NCANode'
Applying dependency management to configuration 'testRuntimeOnly' in project 'NCANode'
Applying dependency management to configuration 'testRuntimeClasspath' in project 'NCANode'
Applying dependency management to configuration 'apiElements' in project 'NCANode'
Applying dependency management to configuration 'runtimeElements' in project 'NCANode'
Applying dependency management to configuration 'developmentOnly' in project 'NCANode'
Applying dependency management to configuration 'productionRuntimeClasspath' in project 'NCANode'
Applying dependency management to configuration 'providedCompile' in project 'NCANode'
Applying dependency management to configuration 'providedRuntime' in project 'NCANode'
Applying dependency management to configuration 'jacocoAgent' in project 'NCANode'
Applying dependency management to configuration 'jacocoAnt' in project 'NCANode'
All projects evaluated.
Selected primary task 'bootRun' from project :
Tasks to be executed: [task ':compileJava', task ':compileGroovy', task ':processResources', task ':classes', task ':bootRunMainClassName', task ':bootRun']
Tasks that were excluded: []
:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileJava FAILED
Resolving global dependency management for project 'NCANode'
Excluding [org.opensaml:opensaml-messaging-api, commons-collections:commons-collections, org.opensaml:opensaml-soap-impl, org.apache.velocity:velocity, com.google.guava:listenablefuture, org.opensaml:opensaml-storage-api, org.checkerframework:checker-qual, com.google.code.findbugs:jsr305, commons-lang:commons-lang, com.google.j2objc:j2objc-annotations, com.google.errorprone:error_prone_annotations]
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 1.249 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find :kalkancrypt-0.7:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
1 actionable task: 1 executed
Watching 1 directories to track changes

**Comment by malikzh** [comment]
Попробуйте сейчас вытянуть изменения и сбилдить, либо можете использовать уже собранную версию: https://github.com/malikzh/NCANode/releases/tag/3.0.0-alpha.1

Спецификация по новой версии находится тут: https://v3.ncanode.kz/swagger-ui/

Скоро обновлю сайт и добавлю подробную документацию.

**Comment by malikzh** [comment]
Уже собранный проект с последними библиотеками kalkancrypt 0.7.2 можете скачать здесь: https://github.com/malikzh/NCANode/releases/tag/3.1.0
