### ISSUE TITLE
В новой версии отсутствует метод получения данных из сертификата

### ISSUE THREAD

**Issue by valexweb** [malikzh/NCANode#136]
В новой версии отсутсвует метод, с помощью которого можно было бы получить информацию не из контейнера pkcs12, а из самого сертификата. Во второй версии такой метод назывался "X509.info" https://ncanode.kz/docs.php?go=68c0077b854fcdb23c567751b1329be3a34447c0
Для чего необходимо? Разного рода проверки на сервере можно выполнять только с сертификатом.

**Comment by malikzh** [comment]
@valexweb добавил: https://github.com/malikzh/NCANode/releases/tag/3.1.0
