### ISSUE TITLE
Ошибка при подписании документа

### ISSUE THREAD

**Issue by abendankan** [malikzh/NCANode#138]
Добрый день!

При подписании документа, выходит ошибка cannot read xml, что мы делаем не так?

**Comment by malikzh** [comment]
Эта ошибка выходит в случае некорректного XML-формата: https://github.com/malikzh/NCANode/blob/master/src/main/java/kz/ncanode/wrapper/DocumentWrapper.java#L48

**Comment by abendankan** [comment]
> 
метод `post` используем
