### ISSUE TITLE
keyAlias есть ли метод получить?

### ISSUE THREAD

**Issue by Eremiteb** [malikzh/NCANode#140]
Есть ли стандартный метод для получения keyAlias? Для тех,кто не на java?

**Comment by malikzh** [comment]
Вообще, параметр keyAlias необязателен в запросах, его можно не указывать. NCANode выберет просто первый алиас в списке. Но, если необходимо получить список алиасов, я добавил метод: https://github.com/malikzh/NCANode/releases/tag/3.2.0
