### ISSUE TITLE
Не получается запустить NCANode в виде дистрибутива war для apache tomcat сервера. Нет документации.

### ISSUE THREAD

**Issue by vprokof** [malikzh/NCANode#142]
Пытаюсь запустить версию NCANode v3.2.0  на tomcat
- установил Apache Tomcat/9.0.65 под Java 17
- выбрал WAR файл для загрузки в виде NCANode.war
- Успешно загрузил. Появился директорий  webapps/NCANode. Сервер перезапустил.
Ожидал увидеть по адресу http://localhost:8080/NCANode/NCANode приветствие,
но получаю    HTTP Status 404 – Не найдено.
В чём может быть проблема ?
Большая просьба дополнить документацию   примерами
- запуска  NCANode на Apache Tomcat
- запросов к tomcat.

**Comment by malikzh** [comment]
Была проблема с иницилизацией сервлета. Точнее её не было. Я исправил это, протестировал в Apache Tomcat 9.

Выкатил исправление: https://github.com/malikzh/NCANode/releases/tag/3.2.1

По поводу документации, я добавлю её при следующем обновлении.

После запуска в Tomcat, для проверки можете использовать этот запрос: http://localhost:8080/NCANode/actuator/health

**Comment by vprokof** [comment]
Процесс пошёл.

Методы
http://localhost:8080/NCANode/xml/sign
http://localhost:14579/xml/sign
Вернули одинаковый ответ.

Пробовал под Redhat.
Заметил, что требуется иметь готовый директорий
 /cache/crl/full с разрешениями tomcat:tomcat
по записи для загрузки отозванных ключей
