### ISSUE TITLE
Проверка подписи Удостоверяющих центров Государственных Органов

### ISSUE THREAD

**Issue by daemao** [malikzh/NCANode#161]
Здравствуйте, при проверке cms, подписанного УцГО, методом cms/verify выдает ошибку  "cannot invoke "java.util.List.stream()" because return value of "java.security.cert.X509Certificate.getExtendedKeyUsage()" is null.
Аналогичная ошибка выходит при методе /x509/info. cms подписанные сертификатами GOST работают исправно.
Подскажите пожалуйста, имеется ли возможность работы с данными сертификатами на сегодняшний день, или я что-то делаю не так?( Спасибо огромное

**Comment by seidakhmet** [comment]
Приветствую. Аналогичная проблема во время проверки xml которые были подписаны УЦ Банков второго уровня. Есть решение проблемы? Или же всё таки лучше свою проверку на php поднять?

**Comment by malikzh** [comment]
https://github.com/malikzh/NCANode/commit/82cb02447bcf75a5922da8f07d700cf66c124b12
