### ISSUE TITLE
CMS Sign flag в сервисе CMS Verification

### ISSUE THREAD

**Issue by Yeras** [malikzh/NCANode#162]
**Describe the bug**
Согласно документации NCALayer Алгоритм формирования ЭЦП через функцию createCMSSignatureBase64 необходимо формировать без данных клиента. Но при формировании подписи без данных клиента и использованию функции createCMSSignatureBase64 с параметрам flag (false) получаем 500 ошибку при обращении к сервису CMS Verify в NCANode. Но при передаче flag(true) получаем корректный ответ от сервиса.

Прошу подсказать, учтено ли это часть в реализации NCA Node или же это новое требование со стороны NCALayer?

**Comment by malikzh** [comment]
нет, в реализации сделано всё согласно примерам из библиотеки kalkancrypt
