### ISSUE TITLE
cms.Verify - 500 ошибка при проверке подписи, когда подпись через метод createCMSSignatureFromBase64 с флагом=false

### ISSUE THREAD

**Issue by Nurbek-K-A** [malikzh/NCANode#163]
Прошу подсказать, как проверить результат подписи с формированный без данных (flag=false) через метод createCMSSignatureFromBase64, получаем ошибку.
При подписи с данными (flag=true) ошибок нет.

1. В запросе подписи в поле "args" в 4 параметр передаем "false":
signRequest = {
    module: 'kz.gov.pki.knca.commonUtils',
    method: 'createCMSSignatureFromBase64',
    args: ['PKCS12', 'SIGNATURE', base64, false],
  };

2. Полученный CMS проверяем через NcaNode cms.verify и получаем ошибку 
Запрос:
{
    "version": "2.0",
    "method": "cms.verify",
    "params": {
        "checkOcsp": true,
        "checkCrl": true,
        "cms": "MIISKwYJKoZIhvcNAQcCoIISHDCCEhgCAQExDzANBglghkgBZQMEAgEFADALBgkqhkiG9w0BBwGgggZi..."
    }
}
Ответ:
{
    "httpCode": 500,
    "message": "Api error: null",
    "status": 5
}

**Comment by malikzh** [comment]
В даный момент мне неизвестен механизм работы метода createCMSSignatureFromBase64, как разберусь сделаю
