### ISSUE TITLE
Docker ARM64

### ISSUE THREAD

**Issue by yuritsuki** [malikzh/NCANode#168]
На M1/M2 много ресурсов потребляет. Просьба добавить поддержку ARM64 для докера. Судя по https://hub.docker.com/_/amazoncorretto есть данный образ с поддержкой данной архитектуры.

**Comment by malikzh** [comment]
С версии 3.3.2 есть поддержка архитектуры ARM64:
https://hub.docker.com/layers/malikzh/ncanode/3.3.2/images/sha256-3c2894dee9dda9b4cd9e3c4fecc426f0be3ebfe21d746ba29d1692e31c48faf0?context=explore
