### ISSUE TITLE
Инструкция

### ISSUE THREAD

**Issue by dastanzholdas** [malikzh/NCANode#170]
Здравствуйте, получили SDK2.0, много файлов и непонятно какой загружать в /lib
Можете скинуть пошаговую инструкцию
Буду благодарен

**Comment by malikzh** [comment]
Для сборки проекта необходимо:

1. Подставить библиотеки kalkancrypt (`knca_provider_jce_kalkan-*.jar` и `kalkancrypt-xmldsig-*.jar`) в директорию lib (Их можно запросить [тут](https://pki.gov.kz/developers/))
2. `./gradlew bootJar` (для jar файла) или `./gradlew bootWar` (для war файла)
