### ISSUE TITLE
Не проходит хэш сумма в base64

### ISSUE THREAD

**Issue by 22tamerlan** [malikzh/NCANode#175]
Добрый день, Малик! Можете подсказать некоторые моменты по вашему сервису https://ncanode.kz/ . При cms sign поле data принимает какие-то определенные форматы значении, по типу байтов или base64? Или же можно кидать обычную хэш сумму без преобразования? У нас хэш сумма файла в base64 при подписании ругается на длину, но тоже время он проходит в сертекс клауд.

**Comment by malikzh** [comment]
Поле data принимает base64:
`
data* | CmsDatastringexample: bG9sIGtlaw==Данные для подписи. ДОЛЖНЫ быть в формате Base64.
-- | --
`

**Comment by malikzh** [comment]
Это сделано для того, чтобы Вы могли передавать любые данные посредством кодирования их в base64
