### ISSUE TITLE
Множественное подписание

### ISSUE THREAD

**Issue by TrunovK** [malikzh/NCANode#177]
Мы у себя в компании развернули NCA Node v3 и успешно с ним работаем. Кроме нескольких ситуаций его работоспособночти вполне хватает.
Но есть ошибки в логике работы с множественным подписанием: 
1.	Если в CMS добавить вторую подпись и потом проверить ее то выходит ошибка. Ее уже регистрировали в Issues [https://github.com/malikzh/NCANode/issues/159](https://github.com/malikzh/NCANode/issues/159)
2.	Также начали тестирование множественного подписания через Egov mobile и результат проверки выдает странные вещи: на 4 подписи почемуто выходит 16 сертификатов. Это больше похоже на ошибку в логике.
a.	Просто тут не понятно, реально ошибка в логике сервиса или действительно кривой файл создается в Егов мобаил. 
b.	Разные сервисы где я проверял дублей не показывают
3.	Кстати, в апи /cms/virify есть ошибка в описании структуры результата:
{
  "status": 200,
  "message": "OK",
  "valid": true,
  "signers": [
    {
      "**signers**": [
        {
          "valid": true,
          "revocations": [

В общем, прошу подсказать как я могу самостоятельно найти и отладить программный код и что нужно, чтобы положить изменений в гит на проверку?
Могу ли я использовать для этого VS Code или нужно использовать Eclipce? Или нужна другая IDE? Как лучше и правильно отладить и после этого скомпилировать исполняемые jar/war файлы?
Беглый поиск по интернету быстрого результата не дал, по этому проще обратиться сюда, чем тратить время на «изобретение велосипеда заново».

Заранее благодарю за скорый ответ.

П.С. По ожиданиям в ближайший 1-2 месяца Nitec выпустят обновление приложений, и те, кто уже пользуется множественным подписанием, могут как и мы получить проблемы с подписанием и проверкой подписанных файлов.

**Comment by malikzh** [comment]
Я использую Intellij IDEA и в нём можно отладить проект, PR я рассматриваю всегда, а касательно issues, как будет время
