### ISSUE TITLE
Перезапись времени подписи tsp при множественном подписании

### ISSUE THREAD

**Issue by NigmetovTimur** [malikzh/NCANode#183]
Здравствуйте. При последовательной подписи обновляется и дублируется у всех подписантов поле genTime.
То есть подписал последний человек и все данные ключа genTime у всех обновляются до времени подписи последнего подписавшего. Думаю это серьезный баг. Ну и думаю из-за него не проходит cms проверку на https://ezsigner.kz/#!/main и https://sigex.kz/ @malikzh

**Comment by malikzh** [comment]
https://github.com/malikzh/NCANode/commit/bbb03770144fae7c33c9ae98982e6ce43cf9778b
