### ISSUE TITLE
Подпись QR

### ISSUE THREAD

**Issue by Rashid2kaz** [malikzh/NCANode#186]
Привет!
Понятно что твой докер использует весь Казахстан, за что все тебе благодарны.
Но наглости человеческой нет предела)))

Планируешь ли реализовать в сервере поддержку подписи ЭЦП по QR?

**Comment by TrunovK** [comment]
Сомневаюсь что чтото подобное будет сделано, да и это скорее не реально. Можете дело в не понимании процесса?)
Подписанные через QR файлы xml и cms прекрасно проверяются, а если стоит задача именно подписания, то есть 2 пути решения: идти в SmartBridge и подавать заявку, в целом не сложно; и воспользоваться готовым сервисом [https://sigex.kz/support/developers/#egov-qr](https://sigex.kz/support/developers/#egov-qr).

**Comment by Rashid2kaz** [comment]
Может я действительно чего-то не понимаю. Если вы изучали https://sigex.kz/support/developers/#egov-qr, то обратили внимание, что там используется 3 API метода, сначала получаешь QR, потом отправляешь файлы на подпись и получаешь сами подписи. Вот неплохо было бы не гонять трафик между сервисами, а отправлять такие запросы к своему серверу ncanode, аналогично как при обычной подписи ЭЦП. Естественно, если это возможно.
А насчет SmartBridge я в курсе, но это не от меня зависит, я всего лишь разраб.

**Comment by TrunovK** [comment]
А тут в любом случае, либо сторонний сервис, либо свой собственный. 3 АПИ сигекса достаточно простые и можно буквально на коленке запустить работающее решение, хоть через постман чтото подписать. Если нет желания использовать посредника, то только через СБ, тем более что структура данных для интеграции  там тоже не сложная. По своему опыту скажу что вся больше завязано на бизнеслогику, которая у каждого решения уникальна, а чтобы отдать json много делать не надо)

**Comment by Rashid2kaz** [comment]
Ну у сигекса там готовый файл js есть, использовать действительно вообще не сложно. Просто хотелось бы без посредника. Пока инфы по SmartBridge нету. Сейчас на сервере портала запущен докер ncanode, когда подписываем с помощью ЭЦП, все запросы к нему, вот хотелось бы чтобы при подписании QR тоже обращаться к нему. Когда получу инфу по SmartBridge, станет понятно как лучше.

**Comment by TrunovK** [comment]
https://sb.egov.kz/smart-bridge/services/passport/NITEC-S-5096 тут достаточно зайти на портал под любым ЭЦП юрлица (сотрудника). К сожалению ИП не подойдет, у них нет юр ключей.
Там кстати есть еще понятие "кросс подписание", когда есть ссылка например в почте, и по ней открывается приложение егов для подписания (как будто был отсканирован QR). Там разработчики в принципе отвечают и помогают разобраться что к чему, тоже ничего сложного.

**Comment by guaricema** [comment]
ИМХО, NCANode реализует функционал официального SDK, в котором нет ничего от QR. QR — это просто надстройка, реализованная в виде сервиса. Вам так и так придется гонять данные в третью точку.
