### ISSUE TITLE
Ошибка 500 при проверке /pkcs12/info

### ISSUE THREAD

**Issue by Talgin** [malikzh/NCANode#191]
**Describe the bug**
При использовании запроса /pkcs12/info возвращает:
{
    "status": 500,
    "message": "class kz.gov.pki.kalkan.asn1.DERSequence cannot be cast to class kz.gov.pki.kalkan.asn1.DERInteger (kz.gov.pki.kalkan.asn1.DERSequence and kz.gov.pki.kalkan.asn1.DERInteger are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @6f539caf)"
}
Тестовый запрос возвращает значения как в примере с документации. 

Сервер был поднят на локальной машине с использованием докера. 

**To Reproduce**
1. Запрос на http://localhost:14579/pkcs12/info с действующим персональным ключом в параметре key и паролем от него в password, пример был взят с https://v3.ncanode.kz/swagger-ui/#/Info/post_pkcs12_info 
2. See error

**Expected behavior**
Ожидал увидеть информацию о ключе

  **Screenshots**
  ![image](https://github.com/malikzh/NCANode/assets/5124655/2f9949cf-183b-424d-85ce-f6de625c8853)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: chrome

**Comment by DanShR** [comment]
столкнулся с такой же ошибкой, оказалось что неправильно указывал ключ, нужно прям файл ключа преобразовывать в base64. Вы наверное берете то что между "-----BEGIN CERTIFICATE-----" и "-----END CERTIFICATE-----"
