### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by RaiMX** [malikzh/NCANode#196]
На версии 2 небыло проблем с CORS (работает через nginx).
На версии 3 начал ругаться на  CORS когда с другого домена отправляю запросы (через nginx, так же как и было с версией 2)

Всё работает если с домена например будучи на mydomain.com отправляю запрос на mydomain.com/ncanode.
Но когда на admin.mydomain.com отправляю на mydomain.com/ncanode - не работает теперь с версией 3 = Выдаёт CORS ошибку

Вот так прописал в nginx

```
location /ncanode {
    rewrite ^/ncanode(.*) $1 break;
    proxy_pass http://ncanode-app:14579;
    proxy_pass_header Server;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
}

```

**Comment by RaiMX** [comment]
Вот так прописал в nginx
```
location /ncanode {
    rewrite ^/ncanode(.*) $1 break;
    proxy_pass http://ncanode-app:14579;
    proxy_pass_header Server;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
}
```

**Comment by RaiMX** [comment]
@malikzh Салем,

Подскажи пожалуйста. Я сам посмотрел бы, просто джаву не знаю

**Comment by malikzh** [comment]
Салем,
С версии 3.3.3 отключен CORS
