### ISSUE TITLE
"ocsp.pki.gov.kz: Try again" причина отзыва сертификата

### ISSUE THREAD

**Issue by bliny-so-smetanoi** [malikzh/NCANode#198]
Получаю ответ от nca node ocsp.pki.gov.kz: Try again 

данный ответ воспроизводится по ендпоинту /xml/verify , но выходит через раз
```
"url": "/xml/verify",
  "response": {
    "Valid": false,
    "Signers": [
      {
        "Valid": false,
        "Revocations": [
          {
            "Revoked": false,
            "By": "OCSP",
            "RevocationTime": null,
            "Reason": "ocsp.pki.gov.kz: Try again"
          }
        ],
```
        
 nca node развернут в докере
 подскажите, в чем может быть проблема?

**Comment by malikzh** [comment]
Это отвечает сервер ocsp, возможно у них какие-то проблемы
