### ISSUE TITLE
Юридическое обоснование

### ISSUE THREAD

**Issue by blumfontein** [malikzh/NCANode#24]
Здравствуйте, у вас отличный проект. Можете подсказать с юридической точки зрения, насколько правомерно передавать ключи пользователей на свой сервер? Т.е. могу ли я использовать ваш сервер на проекте, на котором любой пользователь может зайти и что-то подписать? Или пользоваться может только ограниченный круг, который подписал определнное соглашение?

**Comment by malikzh** [comment]
Здравствуйте. Благодарю.

Сама технология асимметричного шифрования подразумевает, что секретные ключи никому передаваться не будут. Если необходимо, чтобы пользователь подписал какой нибудь документ или данные, то лучше использовать для этого NCALayer. Если же например Вы работаете с налоговой или гос базой на стороне сервера, и Вам нужно подписать какой-то документ от себя, то можете использовать NCANode.
