### ISSUE TITLE
Подписываю один документ с двумя ЭЦП, но в signers показывает только один

### ISSUE THREAD

**Issue by sbeka** [malikzh/NCANode#40]
Здравствуйте! 

Подписываю один документ через cms.sign (2.0) с одним ЭЦП.
В cms.verify проверяю подписанный CMS, там все правильно показывает.

Потом этот CMS подписываю снова через другой ЭЦП.

и снова проверяю через cms.verify полученный CMS, а там показывает только последний подписавший ЭЦП.

проверил через RAW.sign (1.0), тоже самое.

Вопрос: что нужно сделать чтобы после подписи сохранились все подписи?

Пробовал подписать через https://ezsigner.kz/ там все показывает (все подписи).

**Comment by malikzh** [comment]
Здравствуйте, @sbeka . Начиная с NCANode версии 2.0.0, было добавлено новое API и реализован метод: `cms.sign`

Он поддерживает подпись несколькими участниками. Документацию метода можете посмотреть здесь: https://ncanode.kz/docs.php?go=e3ebdc77c47d8fec8ce37ef76253a712790d5c89

**Comment by sbeka** [comment]
> Здравствуйте, @sbeka . Начиная с NCANode версии 2.0.0, было добавлено новое API и реализован метод: `cms.sign`
> 
> Он поддерживает подпись несколькими участниками. Документацию метода можете посмотреть здесь: https://ncanode.kz/docs.php?go=e3ebdc77c47d8fec8ce37ef76253a712790d5c89
> 
> UPD: Вам необходимо передавать в массиве `p12array` сразу все ключи для подписи

у меня такая ситуация, нужно подписать документы поочередно, то есть сразу несколько ключей не отправляется.

Есть личный кабинет пользователей, к примеру 5-6 человеку нужно подписать один документ. Они может подписать в разные время. Как быть в таком случае?

**Comment by sbeka** [comment]
@malikzh можете помочь с ответом?

**Comment by malikzh** [comment]
В NCANode нет возможности последовательной подписи, можно только сразу со всеми подписями сформировать CMS файл. Если Вам не важен именно формат CMS, то можете использовать xmldsig подпись.

**Comment by artem-astafyev** [comment]
Добрый день! 
Столкнулись с необходимостью последовательной подписи, что вы подразумеваете под **xmldsig подписью**?
Какая схема работы предполагается для последовательной подписи?

Ранее мы пробовали метод XML.sign для последовательной подписи, но в таком случает после второй подписи метод XML.verify выдает ошибку.
