### ISSUE TITLE
Добавить в документацию клиент NCANode для Go

### ISSUE THREAD

**Issue by malikzh** [malikzh/NCANode#44]
Добавить клиент:
https://github.com/danikarik/ncanode-go

**Comment by danikarik** [comment]
Первый релиз [клиента](https://github.com/danikarik/ncanode-go) готов.

**Comment by danikarik** [comment]
@malikzh написал Javascript [клиента](https://github.com/seithq/ncalayerjs) для работы с `NCALayer`. Может кому-то понадобиться при построении фронтенда.
Можно разместить ссылку на библиотеку, если возможно? Конечно, на Ваше усмотрение.
