### ISSUE TITLE
Настроить автоматический билд в Docker Hub

### ISSUE THREAD

**Issue by malikzh** [malikzh/NCANode#46]
Необходимо настроить автоматическую сборку образа Docker. Инструкция:
https://docs.travis-ci.com/user/docker/

**Comment by danikarik** [comment]
@malikzh можно публиковать образ на [GitHub Docker Registry](https://github.com/features/packages) через [GitHub Actions](https://github.com/features/actions). Будет более нативная интеграция с CI/CD.
