### ISSUE TITLE
Привет, отличная работа

### ISSUE THREAD

**Issue by ivan01march** [malikzh/NCANode#53]
Думаю стоит добавить эти строки в Dockerfile.build:
RUN wget -P ./ca/root https://pki.gov.kz/cert/root_rsa.crt
RUN wget -P ./ca/root https://pki.gov.kz/cert/root_gost.crt
RUN wget -P ./ca/trusted https://pki.gov.kz/cert/pki_rsa.crt
RUN wget -P ./ca/trusted https://pki.gov.kz/cert/pki_gost.crt
RUN wget -P ./ca/trusted https://pki.gov.kz/cert/nca_rsa.crt
RUN wget -P ./ca/trusted https://pki.gov.kz/cert/nca_gost.crt

**Comment by malikzh** [comment]
@ivan01march Благодарю, да сегодня вечером добавлю)
