### ISSUE TITLE
При подписании ошибка Api error: http://crl.pki.gov.kz/d_rsa.crl

### ISSUE THREAD

**Issue by Zhangirkhan** [malikzh/NCANode#54]
При подписании с 1 первой версии выходит ошибка 
Api error: http://crl.pki.gov.kz/d_rsa.crl
по ссылке такого файла нет. Можете ли вы обратиться в Национальный удостоверящей центр Республики Казахстан
чтобы исправить эту ошибку. Благодарен. 
если что в файле ncanode.ini думаю можно убрать ссылку на этот файл? или я не прав

**Comment by Zhangirkhan** [comment]
В конечном итоге остались вот эти вот документы
;; Список урлов для скачивания CRL. URL необходимо разделять пробелами.
crl_urls=http://crl.pki.gov.kz/nca_rsa.crl http://crl.pki.gov.kz/nca_gost.crl http://crl.pki.gov.kz/nca_d_rsa.crl http://crl.pki.gov.kz/nca_d_gost.crl

**Comment by DimaSavchenko** [comment]
@Zhangirkhan @malikzh есть новости?
запрос из примера не отрабатывает https://ncanode.kz/docs.php?go=9797704344e3175efb3260fbc5e58dac6c2fed3d

`{
    "message": "Api error: http://crl.pki.gov.kz/rsa.crl",
    "status": 5
}`

**Comment by blumfontein** [comment]
Добрый день, та же проблема. При иницализации докер контейнера в логах такая ошибка:

9/29/2020 5:01:34 PMDownloading CRL from: http://crl.pki.gov.kz/rsa.crl ...
9/29/2020 5:01:34 PMjava.io.FileNotFoundException: http://crl.pki.gov.kz/rsa.crl
9/29/2020 5:01:34 PM	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
9/29/2020 5:01:34 PM	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
9/29/2020 5:01:34 PM	at java.net.URL.openStream(URL.java:1045)
9/29/2020 5:01:34 PM	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1456)
9/29/2020 5:01:34 PM	at kz.ncanode.pki.CrlServiceProvider.downloadCrl(CrlServiceProvider.java:167)
9/29/2020 5:01:34 PM	at kz.ncanode.pki.CrlServiceProvider.updateCache(CrlServiceProvider.java:125)
9/29/2020 5:01:34 PM	at kz.ncanode.pki.CrlServiceProvider.<init>(CrlServiceProvider.java:34)
9/29/2020 5:01:34 PM	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
9/29/2020 5:01:34 PM	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
9/29/2020 5:01:34 PM	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
9/29/2020 5:01:34 PM	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
9/29/2020 5:01:34 PM	at kz.ncanode.ioc.ServiceContainer.createInstance(ServiceContainer.java:104)
9/29/2020 5:01:34 PM	at kz.ncanode.ioc.ServiceContainer.resolveDependencies(ServiceContainer.java:113)
9/29/2020 5:01:34 PM	at kz.ncanode.ioc.ServiceContainer.createInstance(ServiceContainer.java:83)
9/29/2020 5:01:34 PM	at kz.ncanode.ioc.ServiceContainer.resolveDependencies(ServiceContainer.java:113)
9/29/2020 5:01:34 PM	at kz.ncanode.ioc.ServiceContainer.createInstance(ServiceContainer.java:83)
9/29/2020 5:01:34 PM	at kz.ncanode.ioc.ServiceContainer.boot(ServiceContainer.java:70)
9/29/2020 5:01:34 PM	at kz.ncanode.Launcher.main(Launcher.java:70)

**Comment by malikzh** [comment]
Здравствуйте, @Zhangirkhan @DimaSavchenko . Да эти файлы были удалены на сервере. Я создал коммит с исправлением этой ошибки. Сейчас только 4 crl используется я их оставил, остальные убрал.

**Comment by malikzh** [comment]
Релиз собирается: https://github.com/malikzh/NCANode/releases/tag/v2.0.2

**Comment by malikzh** [comment]
Новый релиз выпущен: https://github.com/malikzh/NCANode/releases/tag/v2.0.2
Ошибку устранил. Благодарю за обратную связь.

**Comment by blumfontein** [comment]
Докер образ вы не собираете?

**Comment by malikzh** [comment]
@blumfontein который для билда нет, а который для запуска Dockerfile.run он скачивает последнюю версию с гитхаба. А вообще такая задача имеется чтобы Travis ещё и образ деплоил, потому что мне не нравится, что у нас два докерфайла)

**Comment by malikzh** [comment]
Иными словами если Вы перезагрузите контейнер:

```
docker stop ncanode
docker rm ncanode
docker run ncanode ...
```
то должна новая версия развернуться.

**Comment by blumfontein** [comment]
Спасибо разобрались
