### ISSUE TITLE
"kalkanVersion": null

### ISSUE THREAD

**Issue by nurzhan1990** [malikzh/NCANode#57]
Подставил библиотеки из комплекта разработчика (SDK) в директорию /lib.
переименовал файл Dockerfile.build на Dockerfile и запустил команду 
```
   docker build -t malikzh/ncanode .
```
после запустил команду 
```
   docker run -ti -p 14579:14579 malikzh/ncanode
```
и при запросе 
```
{
    "version": "2.0",
    "method": "node.info"
}
```
возвращает 
```
{
    "dateTime": "2020-10-10 07:04:56",
    "timezone": "GMT",
    "kalkanVersion": null,
    "name": "NCANode v2.0.1",
    "message": "",
    "version": "2.0.1",
    "status": 0
}
```

где я делаю не так? спасибо

**Comment by malikzh** [comment]
Здравствуйте.
Да такая проблема есть даже в собранной версии NCANode, пока не знаю почему
это происходит. Но, остальные методы работают исправно, можете не обращать
внимания на этот баг.

сб, 10 окт. 2020 г., 13:10 nurzhan1990 <notifications@github.com>:

**Comment by nurzhan1990** [comment]
извините за глупый вопрос, для чего файл Dockerfile.run? При команде 
```
docker run -ti -p 14579:14579 malikzh/ncanode
```
он к нему не обращается же

**Comment by malikzh** [comment]
> извините за глупый вопрос, для чего файл Dockerfile.run? При команде
> 
> ```
> docker run -ti -p 14579:14579 malikzh/ncanode
> ```
> 
> он к нему не обращается же

Этот докерфайл используется для сборки образа командой:

```bash
docker build -f Dockerfile.run -t malikzh/NCANode
```
