### ISSUE TITLE
Закодированный файл c ключом p12, в формате Base64

### ISSUE THREAD

**Issue by nurzhan1990** [malikzh/NCANode#60]
Чтобы перевести ключ в формат base64, я должен скачать ключ к себе потом перевести в base64? NCALayer как я понял не выдает мне сам ключ или в формате base64. Спасибо

**Comment by malikzh** [comment]
@nurzhan1990 Там получаеся берёте просто файл p12 и то что в нём содержится конвертируете в base64.

Например в bash:

```
base64 -e ./вашключ.p12
```

**Comment by malikzh** [comment]
Это сделано потому, что json это текстовый формат и как таковой нормальной поддержки бинарных данных у него нет.
