### ISSUE TITLE
ezsigner.kz; РЕЗУЛЬТАТ ПРОВЕРКИ – НЕУДАЧНО

### ISSUE THREAD

**Issue by nurzhan1990** [malikzh/NCANode#61]
Почему неудачно, из за того что **Результат проверки TSP**  отсутствует?
Информация об электронном документе

### 1) ПОДПИСАНТ –***** **** ******; РЕЗУЛЬТАТ ПРОВЕРКИ – НЕУДАЧНО
- Результат проверки сертификата | Успешно
- Результат проверки TSP                | Отсутствует метка времени
- Результат проверки подписи        | Успешно
- ИИН | *****
- ФИО | *****
- Серийный номер сертификата | *****
- Срок действия сертификата | 19/08/2020 17:20:07 - 19/08/2021 17:20:07

**Comment by malikzh** [comment]
@nurzhan1990 да, наколько я помню TSP тоже требуется
