### ISSUE TITLE
Клиентская сторона (NCALayer)

### ISSUE THREAD

**Issue by nurzhan1990** [malikzh/NCANode#63]
Как у пользователя забирать ключ p12 и пароль чтобы передать его по api? 

- через NCALayer я как то могу получить сам ключ p12?
- я могу как обычный файл у пользователя забирать его ключ и пароль к себе?  и потом передавать его по api, или это запрещено по закону?

**Comment by malikzh** [comment]
NCANode предназначен только для использования на сервере. А ключ p12 не должен передаваться по сети, тем более приватный ключ, так как это противоречит идее PKI (Public Key Infrastructure). Поэтому для подписи на клиентской стороне следует использовать NCALayer.
