### ISSUE TITLE
java heap space

### ISSUE THREAD

**Issue by hdskz** [malikzh/NCANode#64]
[https://ibb.co/SKtzmbH](url)
Добрый день. Спасибо за отличную разработку. По не определенным причинам выходит ошибка памяти, настройки java памяти увеличивали, не помогает.

**Comment by malikzh** [comment]
Здравствуйте, странное поведение. Сколько времени проходит до выхода этой ошибки?

**Comment by hdskz** [comment]
Дело в том что реализована подпись 4-х документов на базе вашего приложения и ошибка вылетает при подписи первого документа.  Поэтому и вышел на вас как на разработчика с просьбой о помощи. Можете ли вы помочь с дебагом данной проблемы и сколько это будет стоить?
--
Отправлено из Mail.ru для Android пятница, 23 октября 2020г., 20:26 +06:00 от Malik Zharykov  notifications@github.com :

**Comment by hdskz** [comment]
Всё. Спасибо проблема решена. Необходимо было увеличить объем для памяти jvm
--
Отправлено из Mail.ru для Android пятница, 23 октября 2020г., 20:26 +06:00 от Malik Zharykov  notifications@github.com :
