### ISSUE TITLE
Возможность последовательной подписи

### ISSUE THREAD

**Issue by artem-astafyev** [malikzh/NCANode#65]
Добрый день!

Подобный вопрос уже задавали здесь:
[Подписываю один документ с двумя ЭЦП, но в signers показывает только один #40](https://github.com/malikzh/NCANode/issues/40)

Столкнулись с необходимостью последовательной подписи, что вы подразумеваете под **xmldsig** подписью?
Какая схема работы предполагается для последовательной подписи?

Ранее мы пробовали метод **XML.sign** для последовательной подписи, но в таком случае, после второй подписи метод **XML.verify** выдает ошибку.

@malikzh можете помочь с ответом?

**Comment by malikzh** [comment]
Здравствуйте. Включил Вашу доработку в проект.

**Comment by artem-astafyev** [comment]
Спасибо.

**Comment by malikzh** [comment]
Последовательная подпись была реализована в версии v2.3.0
