### ISSUE TITLE
Kalkan Version: null

### ISSUE THREAD

**Issue by anaumov93** [malikzh/NCANode#66]
Здравствуйте.
Запрос
{
    "version": "2.0",
    "method": "node.info"
}
Ответ
{
    "dateTime": "2020-12-06 07:51:22",
    "timezone": "Etc/UTC",
    "kalkanVersion": null,
    "name": "NCANode v2.0.1",
    "message": "",
    "version": "2.0.1",
    "status": 0
}
Собирал с kalkancrypt-0.6.1.jar через mvn clean package. Для сборки отредактировал pom.xml, подставил 0.6.1 вместо 0.6
Что я сделал не так?)

**Comment by malikzh** [comment]
Здравствуйте. Да, такая проблема имеется. Это не критичный баг, по идее должно должно работать нормально.

Вот тут было такое обсуждение: #57

**Comment by anaumov93** [comment]
Спасибо.
Еще вопрос.
Почему при использовании cms.sign и последующей проверке, получается это: 
![Screenshot_4](https://user-images.githubusercontent.com/75561176/101275385-6bb95c80-37cf-11eb-8830-c9c17e9e25cc.png)
