### ISSUE TITLE
TSP v2

### ISSUE THREAD

**Issue by anaumov93** [malikzh/NCANode#67]
Спасибо.
Еще вопрос.
Почему при использовании cms.sign и последующей проверке, получается это: 
![Screenshot_4](https://user-images.githubusercontent.com/75561176/101275385-6bb95c80-37cf-11eb-8830-c9c17e9e25cc.png)
Это при использовании v2. Какой параметр передавать нужно, для создания метки TSP?

_Originally posted by @anaumov93 in https://github.com/malikzh/NCANode/issues/66#issuecomment-739472161_

**Comment by malikzh** [comment]
Попробуйте так:
https://ncanode.kz/docs.php?go=b52dfc5eddafafb5d7c8cccb06c5f0e011a27f3d

И укажите параметры:
tspInCms: true,
createTsp: true,
