### ISSUE TITLE
Получение открепленной cms подписи

### ISSUE THREAD

**Issue by bnurbek** [malikzh/NCANode#68]
Здравствуйте!

Подскажите пожалуйста, как получить открепленную cms подпись?

Наподобие как в NCALayer, когда методу createCAdESFromBase64 в качестве одного из аргументов передается флаг "Включить данные в подпись"

Спасибо!

**Comment by malikzh** [comment]
Спустя 2 года, появилась поддержка откреплённой подписи :)
