### ISSUE TITLE
NCANode в виде дистрибутива war  для apache tomcat сервера

### ISSUE THREAD

**Issue by vprokof** [malikzh/NCANode#84]
Есть ли возможность реализовать дистрибутив NCANode в виде WAR-файла для размещения на apache tomcat сервере ?
Хотелось бы повысить производительность в высоко нагруженных системах.

**Comment by malikzh** [comment]
Добрый день. Очень хороший вопрос. Я планирую делать ещё одно обновление проекта, где-то к середине мая и включу туда данную возможность.

**Comment by vprokof** [comment]
Из наблюдения. Подпись soap посредством  php-java-bridge и модулем java грузил процессор гораздо меньше.
