### ISSUE TITLE
Завис при запуске на сервере

### ISSUE THREAD

**Issue by k-rustemuly** [malikzh/NCANode#85]
**Describe the bug**
Я собрал проект, подставил все библиотеки в папку lib. 
При запуске на сервере java -jar ncav2.jar -config:NCANode.ini
Завис с сообщением
**Starting HTTP server on 0.0.0.0:14141** 
До этого все прекрасно работало. Вчера упал сервис, сегодня вот такая вот проблема. Серверные настройки не менял.

**Comment by k-rustemuly** [comment]
Зарботало

**Comment by Koha2014** [comment]
> Зарботало

как побороли проблему? я пробую на винде запустить, такая же ошибка. Правда проект не собирал заново, а скачал готовый

**Comment by k-rustemuly** [comment]
В телегу @k_rustemuly
