### ISSUE TITLE
Ошибка 500 при запросе XML.verify

### ISSUE THREAD

**Issue by Tical-** [malikzh/NCANode#89]
Привет, отличная работа этим продуктом, подскажите пож-та, посылаем запрос:

{"version":"1.0","method":"XML.verify","params":{"xml":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><PDFFileHash>54d18b40c2de390e912f53c9fb175e64<ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\">\r\n<ds:SignedInfo>\r\n<ds:CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/>\r\n<ds:SignatureMethod Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\"/>\r\n<ds:Reference URI=\"\">\r\n<ds:Transforms>\r\n<ds:Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/>\r\n<ds:Transform Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments\"/>\r\n</ds:Transforms>\r\n<ds:DigestMethod Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\"/>\r\n<ds:DigestValue>w4RBCS9l0/JkxLFgL6VwrY28edp5/yKkZOopRACmYfI=</ds:DigestValue>\r\n</ds:Reference>\r\n</ds:SignedInfo>\r\n<ds:SignatureValue>\r\nJEFeBhXSemuQusnqAq1MSd8hIJeCQt+/vVSyOS33E32BVPqhxYadwsW5Kv09TrOSgky5Ln//bZbD\r\nlBwZ8jQR5cNGNOEECM2/uxl56Ps0ct9CjUEGcRBuED1IzRWt/gYa08ZDCMjwDr/zvB7vibg9FEnS\r\nE6mKxpJfX3IAi3aFf3WzV2lSndRwbtLt39T9De3hYLIbbhYuVzt5HDBpT+uUsGccsGd/2CHyTxgS\r\nJzFBzoztoyuupyR0vUiqTndwvn5soc+a+kGze7ertk/w2GFKHqYqCc9whJzDDFVUSXNDL8DQs4qw\r\nrCslANMJogc0PysQghiRNm6Ak9g7kSLN+CceZg==\r\n</ds:SignatureValue>\r\n<ds:KeyInfo>\r\n<ds:X509Data>\r\n<ds:X509Certificate>\r\nMIIGQzCCBCugAwIBAgIUPic8P9v7crVTrAeVuEfwa+m0cW8wDQYJKoZIhvcNAQELBQAwUjELMAkG\r\nA1UEBhMCS1oxQzBBBgNVBAMMOtKw0JvQotCi0KvSmiDQmtCj05jQm9CQ0J3QlNCr0KDQo9Co0Ksg\r\n0J7QoNCi0JDQm9Cr0pogKFJTQSkwHhcNMjAxMjA5MDMyMzAzWhcNMjExMjA5MDMyMzAzWjCBhTEk\r\nMCIGA1UEAwwb0KjQnNCY0JTQoiDQktCb0JDQlNCY0JzQmNCgMRMwEQYDVQQEDArQqNCc0JjQlNCi\r\nMRgwFgYDVQQFEw9JSU41OTA3MTIzNTAwOTgxCzAJBgNVBAYTAktaMSEwHwYDVQQqDBjQktCb0JDQ\r\nlNCY0JzQmNCg0J7QktCY0KcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCC313P3XHL\r\nH66zlGCDM/mHR94bAQaU8CfI4pdmrvQQcA5Gqy/w+eODgGLBYs4PrxI1T31TvX/qp1sYOOuv+noO\r\nvMdkgEaHlJRseLSHoqZ6dCMx/GsOwL2lhTvqvmg6/DPeYOANYa3lRe8hnPGgyRa3PLUoaQrhhGxX\r\nBymS0SbGhxCimxriPxmU+fl1aWDpByPjjx30DISFcbA4JlySaGLzK8HBLhSsr2/gNcDFChDKXled\r\n4eufiU+LaW+l1dF6mt03+YAgkp0nRlu3Gg/9ban2YTgKKfdn5HB9YKC87hKOyrwqoWcXoCQQSOik\r\nl3QGRL2G8O351TfcdUQcsdKen+3VAgMBAAGjggHbMIIB1zAOBgNVHQ8BAf8EBAMCBsAwHQYDVR0l\r\nBBYwFAYIKwYBBQUHAwQGCCqDDgMDBAEBMA8GA1UdIwQIMAaABFtqdBEwHQYDVR0OBBYEFPrTgU/V\r\nBrZCGeNUL9eFddLx00HeMF4GA1UdIARXMFUwUwYHKoMOAwMCAzBIMCEGCCsGAQUFBwIBFhVodHRw\r\nOi8vcGtpLmdvdi5rei9jcHMwIwYIKwYBBQUHAgIwFwwVaHR0cDovL3BraS5nb3Yua3ovY3BzMFYG\r\nA1UdHwRPME0wS6BJoEeGIWh0dHA6Ly9jcmwucGtpLmdvdi5rei9uY2FfcnNhLmNybIYiaHR0cDov\r\nL2NybDEucGtpLmdvdi5rei9uY2FfcnNhLmNybDBaBgNVHS4EUzBRME+gTaBLhiNodHRwOi8vY3Js\r\nLnBraS5nb3Yua3ovbmNhX2RfcnNhLmNybIYkaHR0cDovL2NybDEucGtpLmdvdi5rei9uY2FfZF9y\r\nc2EuY3JsMGIGCCsGAQUFBwEBBFYwVDAuBggrBgEFBQcwAoYiaHR0cDovL3BraS5nb3Yua3ovY2Vy\r\ndC9uY2FfcnNhLmNlcjAiBggrBgEFBQcwAYYWaHR0cDovL29jc3AucGtpLmdvdi5rejANBgkqhkiG\r\n9w0BAQsFAAOCAgEADHWBFI1HJWSX2D1BpWB/nL9L4OnL+zb5pK/jlzcXCcZ4OkWgELPxsKIgLzt9\r\nyVSK4AkbWwq2F5xtRHnKziTdJ7jeJrtBNcJpvRhtm222SZL8jSX9tOsMCQUaw8QR10G7aSKatKl2\r\nElu4CxnxSIIQEEix5MjehjgizGaoQG7P6EzIeac+iUywG7fIARuB3jY83q50YCnRMerYYZV54zq1\r\nCs/mXEXvlzufyBsIcSg1TKp91ztNd2yeIPfcDLq4AiM0x2J5F8mK8nSPb289HvmIP2qTAKJROkCF\r\npCv5eniSoMRIAXHYz3BkrLHpRwpJS/7Fx2txE0h3tjLI5rErzdguSSf+fpKERE9TEDHktL4rxFki\r\nBMJTVNcTmCoTUNa7p6Z60AuBmbQ1kd+jmeYHcfb4PLAMdF8DRHxuGxU2KC701aUffS9tJsPa0NTN\r\n+rPViNR1A4qvgUdC/Jvj16FSirw91wEakAsPV71xURHAoSJhzXaNmvb/mWl6Lg7GUALstZBfGCCt\r\nrlTTEUlYUE3M01Mb8IO4DJaLxVvmRr0Ro3/+sR5Rc6/5WY6xyAK8A8760W+L0PlDNxu2mfcU3yx9\r\nLbsILZm8/CVbp6A1TzUZSGI5NBV64faKru32hlRzWOlM6IiEE+fWro5g5qK5HtvaejpIfW95ZSnh\r\n+OTsgc09g1RueOQ=\r\n</ds:X509Certificate>\r\n</ds:X509Data>\r\n</ds:KeyInfo>\r\n</ds:Signature></PDFFileHash>","verifyOcsp":true,"verifyCrl":false}}

Получаем ответ {"message":"Api error: Server returned HTTP response code: 500 for URL: http:\/\/ocsp.pki.gov.kz","status":5}
Это 1 из 1000 неудачных ответов, не знаем, что и делать, в чем может быть проблема?

**Comment by malikzh** [comment]
Привет. Не может достучаться до OCSP нашего PKI. вот сюда: http://ocsp.pki.gov.kz

Если не принципиален ocsp, можете юзать проверку на отозванность ключа через CRL. 

```
verifyCrl: true
verifyOcsp: false
```

**Comment by Tical-** [comment]
К сожалению только по этому запросу ошибка.
В других запросах все нормально.
А когда ставлю Crl - true всегда ошибка почему то((

**Comment by malikzh** [comment]
fixed
