### ISSUE TITLE
Доступ через прокси 

### ISSUE THREAD

**Issue by bolatik** [malikzh/NCANode#94]
http://ocsp.pki.gov.kz
http://tsp.pki.gov.kz как реализовать доступ через прокси на эти ресурсы?

**Comment by malikzh** [comment]
Добрый день.

В данный момент в самом NCANode нет возможности подключения через прокси. Но, эту возможность я реализую в следующей версии.

**Comment by nbah1990** [comment]
@bolatik можно попробовать в контейнере HTTP_PROXY и HTTPS_PROXY установить в окружение
