### ISSUE TITLE
FileNotFoundException: http://crl.pki.gov.kz/rsa.crl

### ISSUE THREAD

**Issue by MikhalevAY** [malikzh/NCANode#95]
Добрый день. 

При попытке подписания выходит ошибка что файл не найден http://crl.pki.gov.kz/rsa.crl и Curl соединение сразу закрывается, как решить проблему?

**Comment by malikzh** [comment]
Добрый день. Наверное, в PKI. изменился урл CRL файлов.

Вот тут можно посмотреть: https://pki.gov.kz/developers/

**Comment by malikzh** [comment]
> CRL (Боевой) http://crl.pki.gov.kz/nca_rsa.crl
