### ISSUE TITLE
Ключ p12 - закодированный, в формате Base64 для RAW.sign

### ISSUE THREAD

**Issue by Hrayr-RM** [malikzh/NCANode#96]
Здравствуйте,

Хотим подписать данные для авторизации в гос. системе ИС МПТ. Исходя [из примера запроса](https://ncanode.kz/docs.php?go=b52dfc5eddafafb5d7c8cccb06c5f0e011a27f3d) для подписания данных, нам нужен параметр “p12” - ключ, которым будут подписываться данные (закодированный в формате Base64)

Не могли бы, пожалуйста, подсказать конкретно откуда из ЭЦП (на примере) необходимо брать параметр “p12”, отправляемый в “NCA Node” для подписания и каким образом и в какой формат его необходимо конвертировать? 

Буду очень благодарен за любую помощь!

**Comment by malikzh** [comment]
Добрый день.

Там просто берёте сам ключ, он обычно в формате p12, в base64 и отправляете в NCANode.


Примерно такой код:

```php
<?php

$key = base64_encode(file_get_contents("./ПУТЬКВАШЕМУКЛЮЧУ.p12"));

// и вот его уже подставляете в NCANode в параметр p12.
```

**Comment by Hrayr-RM** [comment]
Спасибо большое, вроде всё получилось!
